name = "gemini-rag-worker"
main = "src/rag.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# KV storage for store metadata
[[kv_namespaces]]
binding = "RAG"
id = "e4bbd1bcec7c4b9f84bed8b644958ac2"


